import { describe, expect, it } from 'vitest'
import { Dvala } from '../../../src/Dvala/Dvala'
import { DvalaError } from '../../../src/errors'

describe('predicates', () => {
  for (const dvala of [new Dvala(), new Dvala({ debug: true })]) {
    describe('function?', () => {
      it('samples', () => {
        expect(dvala.run('function?("")')).toBe(false)
        expect(dvala.run('function?("x")')).toBe(false)
        expect(dvala.run('function?(1)')).toBe(false)
        expect(dvala.run('function?(0)')).toBe(false)
        expect(dvala.run('function?([])')).toBe(false)
        expect(dvala.run('function?({})')).toBe(false)
        expect(dvala.run('function?(null)')).toBe(false)
        expect(dvala.run('function?(true)')).toBe(false)
        expect(dvala.run('function?(false)')).toBe(false)
        expect(dvala.run('function?(+)')).toBe(true)
        expect(dvala.run('function?(-> $ - 1)')).toBe(true)
        expect(() => dvala.run('function?()')).toThrow(DvalaError)
        expect(() => dvala.run('function?("k", "k")')).toThrow(DvalaError)
      })
    })

    describe('string?', () => {
      it('samples', () => {
        expect(dvala.run('string?("")')).toBe(true)
        expect(dvala.run('string?("x")')).toBe(true)
        expect(dvala.run('string?(1)')).toBe(false)
        expect(dvala.run('string?(0)')).toBe(false)
        expect(dvala.run('string?([])')).toBe(false)
        expect(dvala.run('string?({})')).toBe(false)
        expect(dvala.run('string?(null)')).toBe(false)
        expect(dvala.run('string?(true)')).toBe(false)
        expect(dvala.run('string?(false)')).toBe(false)
        expect(dvala.run('string?(+)')).toBe(false)
        expect(dvala.run('string?(+)')).toBe(false)
        expect(() => dvala.run('string?()')).toThrow(DvalaError)
        expect(() => dvala.run('string?("k", "k")')).toThrow(DvalaError)
      })
    })

    describe('number?', () => {
      it('samples', () => {
        expect(dvala.run('number?(1)')).toBe(true)
        expect(dvala.run('number?(0)')).toBe(true)
        expect(dvala.run('number?(-1)')).toBe(true)
        expect(dvala.run('number?(-1.123)')).toBe(true)
        expect(dvala.run('number?(0.123)')).toBe(true)
        expect(dvala.run('number?("")')).toBe(false)
        expect(dvala.run('number?("x")')).toBe(false)
        expect(dvala.run('number?([])')).toBe(false)
        expect(dvala.run('number?({})')).toBe(false)
        expect(dvala.run('number?(null)')).toBe(false)
        expect(dvala.run('number?(false)')).toBe(false)
        expect(dvala.run('number?(true)')).toBe(false)
        expect(dvala.run('number?(+)')).toBe(false)
        expect(dvala.run('number?(+)')).toBe(false)
        expect(() => dvala.run('number?()')).toThrow(DvalaError)
        expect(() => dvala.run('number?(1, 2)')).toThrow(DvalaError)
      })
    })

    describe('integer?', () => {
      it('samples', () => {
        expect(dvala.run('integer?(1)')).toBe(true)
        expect(dvala.run('integer?(0)')).toBe(true)
        expect(dvala.run('integer?(-1)')).toBe(true)
        expect(dvala.run('integer?(-1.123)')).toBe(false)
        expect(dvala.run('integer?(0.123)')).toBe(false)
        expect(dvala.run('integer?("")')).toBe(false)
        expect(dvala.run('integer?("x")')).toBe(false)
        expect(dvala.run('integer?([])')).toBe(false)
        expect(dvala.run('integer?({})')).toBe(false)
        expect(dvala.run('integer?(null)')).toBe(false)
        expect(dvala.run('integer?(false)')).toBe(false)
        expect(dvala.run('integer?(true)')).toBe(false)
        expect(dvala.run('integer?(+)')).toBe(false)
        expect(dvala.run('integer?(+)')).toBe(false)
        expect(() => dvala.run('integer?()')).toThrow(DvalaError)
        expect(() => dvala.run('integer?(1, 2)')).toThrow(DvalaError)
      })
    })

    describe('boolean?', () => {
      it('samples', () => {
        expect(dvala.run('boolean?(1)')).toBe(false)
        expect(dvala.run('boolean?(0)')).toBe(false)
        expect(dvala.run('boolean?(-1)')).toBe(false)
        expect(dvala.run('boolean?(-1.123)')).toBe(false)
        expect(dvala.run('boolean?(0.123)')).toBe(false)
        expect(dvala.run('boolean?("")')).toBe(false)
        expect(dvala.run('boolean?("x")')).toBe(false)
        expect(dvala.run('boolean?([])')).toBe(false)
        expect(dvala.run('boolean?({})')).toBe(false)
        expect(dvala.run('boolean?(null)')).toBe(false)
        expect(dvala.run('boolean?(false)')).toBe(true)
        expect(dvala.run('boolean?(true)')).toBe(true)
        expect(dvala.run('boolean?(+)')).toBe(false)
        expect(dvala.run('boolean?(+)')).toBe(false)
        expect(() => dvala.run('boolean?()')).toThrow(DvalaError)
        expect(() => dvala.run('boolean?(true, false)')).toThrow(DvalaError)
      })
    })

    describe('null?', () => {
      it('samples', () => {
        expect(dvala.run('null?(1)')).toBe(false)
        expect(dvala.run('null?(0)')).toBe(false)
        expect(dvala.run('null?(-1)')).toBe(false)
        expect(dvala.run('null?(-1.123)')).toBe(false)
        expect(dvala.run('null?(0.123)')).toBe(false)
        expect(dvala.run('null?("")')).toBe(false)
        expect(dvala.run('null?("x")')).toBe(false)
        expect(dvala.run('null?([])')).toBe(false)
        expect(dvala.run('null?({})')).toBe(false)
        expect(dvala.run('null?(null)')).toBe(true)
        expect(dvala.run('null?(false)')).toBe(false)
        expect(dvala.run('null?(true)')).toBe(false)
        expect(dvala.run('null?(+)')).toBe(false)
        expect(dvala.run('null?(+)')).toBe(false)
        expect(() => dvala.run('null?()')).toThrow(DvalaError)
        expect(() => dvala.run('null?(true, false)')).toThrow(DvalaError)
      })
    })

    describe('zero?', () => {
      it('samples', () => {
        expect(dvala.run('zero?(1)')).toBe(false)
        expect(dvala.run('zero?(0)')).toBe(true)
        expect(dvala.run('zero?(0.0)')).toBe(true)
        expect(dvala.run('zero?(-0)')).toBe(true)
        expect(dvala.run('zero?(0 / -1)')).toBe(true)
        expect(dvala.run('zero?(-1)')).toBe(false)
        expect(() => dvala.run('zero?()')).toThrow(DvalaError)
        expect(() => dvala.run('zero?("")')).toThrow(DvalaError)
        expect(() => dvala.run('zero?(true)')).toThrow(DvalaError)
        expect(() => dvala.run('zero?(false)')).toThrow(DvalaError)
        expect(() => dvala.run('zero?(null)')).toThrow(DvalaError)
        expect(() => dvala.run('zero?({})')).toThrow(DvalaError)
        expect(() => dvala.run('zero?([])')).toThrow(DvalaError)
      })
    })

    describe('pos?', () => {
      it('samples', () => {
        expect(dvala.run('pos?(1)')).toBe(true)
        expect(dvala.run('pos?(0.1)')).toBe(true)
        expect(dvala.run('pos?(0)')).toBe(false)
        expect(dvala.run('pos?(-0)')).toBe(false)
        expect(dvala.run('pos?(0 / -1)')).toBe(false)
        expect(dvala.run('pos?(-1)')).toBe(false)
        expect(() => dvala.run('pos?()')).toThrow(DvalaError)
        expect(() => dvala.run('pos?("")')).toThrow(DvalaError)
        expect(() => dvala.run('pos?(true)')).toThrow(DvalaError)
        expect(() => dvala.run('pos?(false)')).toThrow(DvalaError)
        expect(() => dvala.run('pos?(null)')).toThrow(DvalaError)
        expect(() => dvala.run('pos?({})')).toThrow(DvalaError)
        expect(() => dvala.run('pos?([])')).toThrow(DvalaError)
      })
    })

    describe('neg?', () => {
      it('samples', () => {
        expect(dvala.run('neg?(1)')).toBe(false)
        expect(dvala.run('neg?(0)')).toBe(false)
        expect(dvala.run('neg?(-0)')).toBe(false)
        expect(dvala.run('neg?(0 / -1)')).toBe(false)
        expect(dvala.run('neg?(-1)')).toBe(true)
        expect(() => dvala.run('neg?()')).toThrow(DvalaError)
        expect(() => dvala.run('neg?("")')).toThrow(DvalaError)
        expect(() => dvala.run('neg?(true)')).toThrow(DvalaError)
        expect(() => dvala.run('neg?(false)')).toThrow(DvalaError)
        expect(() => dvala.run('neg?(null)')).toThrow(DvalaError)
        expect(() => dvala.run('neg?({})')).toThrow(DvalaError)
        expect(() => dvala.run('neg?([])')).toThrow(DvalaError)
      })
    })

    describe('even?', () => {
      it('samples', () => {
        expect(dvala.run('even?(1)')).toBe(false)
        expect(dvala.run('even?(0)')).toBe(true)
        expect(dvala.run('even?(-0)')).toBe(true)
        expect(dvala.run('even?(0 / -1)')).toBe(true)
        expect(dvala.run('even?(-1)')).toBe(false)
        expect(dvala.run('even?(-10)')).toBe(true)
        expect(dvala.run('even?(-2.001)')).toBe(false)
        expect(dvala.run('even?(4)')).toBe(true)
        expect(() => dvala.run('even?()')).toThrow(DvalaError)
        expect(() => dvala.run('even?("")')).toThrow(DvalaError)
        expect(() => dvala.run('even?(true)')).toThrow(DvalaError)
        expect(() => dvala.run('even?(false)')).toThrow(DvalaError)
        expect(() => dvala.run('even?(null)')).toThrow(DvalaError)
        expect(() => dvala.run('even?({})')).toThrow(DvalaError)
        expect(() => dvala.run('even?([])')).toThrow(DvalaError)
      })
    })

    describe('odd?', () => {
      it('samples', () => {
        expect(dvala.run('odd?(1)')).toBe(true)
        expect(dvala.run('odd?(0)')).toBe(false)
        expect(dvala.run('odd?(-0)')).toBe(false)
        expect(dvala.run('odd?(0 / -1)')).toBe(false)
        expect(dvala.run('odd?(-1)')).toBe(true)
        expect(dvala.run('odd?(-10)')).toBe(false)
        expect(dvala.run('odd?(-2.001)')).toBe(false)
        expect(dvala.run('odd?(4)')).toBe(false)
        expect(dvala.run('odd?(5)')).toBe(true)
        expect(() => dvala.run('odd?()')).toThrow(DvalaError)
        expect(() => dvala.run('odd?("")')).toThrow(DvalaError)
        expect(() => dvala.run('odd?(true)')).toThrow(DvalaError)
        expect(() => dvala.run('odd?(false)')).toThrow(DvalaError)
        expect(() => dvala.run('odd?(null)')).toThrow(DvalaError)
        expect(() => dvala.run('odd?({})')).toThrow(DvalaError)
        expect(() => dvala.run('odd?([])')).toThrow(DvalaError)
      })
    })

    describe('array?', () => {
      it('samples', () => {
        expect(dvala.run('array?(1)')).toBe(false)
        expect(dvala.run('array?(0)')).toBe(false)
        expect(dvala.run('array?(-1)')).toBe(false)
        expect(dvala.run('array?(-1.123)')).toBe(false)
        expect(dvala.run('array?(0.123)')).toBe(false)
        expect(dvala.run('array?("")')).toBe(false)
        expect(dvala.run('array?("x")')).toBe(false)
        expect(dvala.run('array?([])')).toBe(true)
        expect(dvala.run('array?([1, 2, 3])')).toBe(true)
        expect(dvala.run('array?({})')).toBe(false)
        expect(dvala.run('array?(null)')).toBe(false)
        expect(dvala.run('array?(false)')).toBe(false)
        expect(dvala.run('array?(true)')).toBe(false)
        expect(dvala.run('array?(+)')).toBe(false)
        expect(() => dvala.run('array?()')).toThrow(DvalaError)
        expect(() => dvala.run('array?(true, false)')).toThrow(DvalaError)
      })
    })

    describe('collection?', () => {
      it('samples', () => {
        expect(dvala.run('collection?(1)')).toBe(false)
        expect(dvala.run('collection?(0)')).toBe(false)
        expect(dvala.run('collection?(-1)')).toBe(false)
        expect(dvala.run('collection?(-1.123)')).toBe(false)
        expect(dvala.run('collection?(0.123)')).toBe(false)
        expect(dvala.run('collection?("")')).toBe(true)
        expect(dvala.run('collection?("x")')).toBe(true)
        expect(dvala.run('collection?([])')).toBe(true)
        expect(dvala.run('collection?([1, 2, 3])')).toBe(true)
        expect(dvala.run('collection?({})')).toBe(true)
        expect(dvala.run('collection?({ a: 1 })')).toBe(true)
        expect(dvala.run('collection?(null)')).toBe(false)
        expect(dvala.run('collection?(false)')).toBe(false)
        expect(dvala.run('collection?(true)')).toBe(false)
        expect(dvala.run('collection?(+)')).toBe(false)
        expect(dvala.run('collection?(+)')).toBe(false)
        expect(() => dvala.run('collection?()')).toThrow(DvalaError)
        expect(() => dvala.run('collection?(true, false)')).toThrow(DvalaError)
      })
    })

    describe('sequence?', () => {
      it('samples', () => {
        expect(dvala.run('sequence?(1)')).toBe(false)
        expect(dvala.run('sequence?(0)')).toBe(false)
        expect(dvala.run('sequence?(-1)')).toBe(false)
        expect(dvala.run('sequence?(-1.123)')).toBe(false)
        expect(dvala.run('sequence?(0.123)')).toBe(false)
        expect(dvala.run('sequence?("")')).toBe(true)
        expect(dvala.run('sequence?("x")')).toBe(true)
        expect(dvala.run('sequence?([])')).toBe(true)
        expect(dvala.run('sequence?([1, 2, 3])')).toBe(true)
        expect(dvala.run('sequence?({})')).toBe(false)
        expect(dvala.run('sequence?({ a: 1 })')).toBe(false)
        expect(dvala.run('sequence?(null)')).toBe(false)
        expect(dvala.run('sequence?(false)')).toBe(false)
        expect(dvala.run('sequence?(true)')).toBe(false)
        expect(dvala.run('sequence?(+)')).toBe(false)
        expect(dvala.run('sequence?(+)')).toBe(false)
        expect(() => dvala.run('sequence?()')).toThrow(DvalaError)
        expect(() => dvala.run('sequence?(true, false)')).toThrow(DvalaError)
      })
    })

    describe('object?', () => {
      it('samples', () => {
        expect(dvala.run('object?(1)')).toBe(false)
        expect(dvala.run('object?(0)')).toBe(false)
        expect(dvala.run('object?(-1)')).toBe(false)
        expect(dvala.run('object?(-1.123)')).toBe(false)
        expect(dvala.run('object?(0.123)')).toBe(false)
        expect(dvala.run('object?("")')).toBe(false)
        expect(dvala.run('object?("x")')).toBe(false)
        expect(dvala.run('object?([])')).toBe(false)
        expect(dvala.run('object?(object("x", 10))')).toBe(true)
        expect(dvala.run('object?(null)')).toBe(false)
        expect(dvala.run('object?(regexp("abc"))')).toBe(false)
        expect(dvala.run('object?(false)')).toBe(false)
        expect(dvala.run('object?(true)')).toBe(false)
        expect(dvala.run('object?(+)')).toBe(false)
        expect(dvala.run('object?(+)')).toBe(false)
        expect(() => dvala.run('object?()')).toThrow(DvalaError)
        expect(() => dvala.run('object?(true, false)')).toThrow(DvalaError)
      })
    })

    describe('regexp?', () => {
      it('samples', () => {
        expect(dvala.run('regexp?(1)')).toBe(false)
        expect(dvala.run('regexp?(0)')).toBe(false)
        expect(dvala.run('regexp?(-1)')).toBe(false)
        expect(dvala.run('regexp?(-1.123)')).toBe(false)
        expect(dvala.run('regexp?(0.123)')).toBe(false)
        expect(dvala.run('regexp?("")')).toBe(false)
        expect(dvala.run('regexp?("x")')).toBe(false)
        expect(dvala.run('regexp?([])')).toBe(false)
        expect(dvala.run('regexp?(object("x", 10))')).toBe(false)
        expect(dvala.run('regexp?(null)')).toBe(false)
        expect(dvala.run('regexp?(regexp("abc"))')).toBe(true)
        expect(dvala.run('regexp?(false)')).toBe(false)
        expect(dvala.run('regexp?(true)')).toBe(false)
        expect(dvala.run('regexp?(+)')).toBe(false)
        expect(dvala.run('regexp?(+)')).toBe(false)
        expect(() => dvala.run('regexp?()')).toThrow(DvalaError)
        expect(() => dvala.run('regexp?(true, false)')).toThrow(DvalaError)
      })
    })

    describe('finite?', () => {
      it('samples', () => {
        expect(dvala.run('finite?(1)')).toBe(true)
        expect(dvala.run('finite?(0)')).toBe(true)
        expect(dvala.run('finite?(1 / 0)')).toBe(false)
        expect(dvala.run('finite?(-1 / 0)')).toBe(false)
        expect(() => dvala.run('finite?(sqrt(-1))')).toThrow(DvalaError)
      })
    })

    describe('positive-infinity?', () => {
      it('samples', () => {
        expect(dvala.run('positive-infinity?(1)')).toBe(false)
        expect(dvala.run('positive-infinity?(0)')).toBe(false)
        expect(dvala.run('positive-infinity?(1 / 0)')).toBe(true)
        expect(dvala.run('positive-infinity?(-1 / 0)')).toBe(false)
        expect(() => dvala.run('positive-infinity?(sqrt(-1))')).toThrow(DvalaError)
      })
    })

    describe('negative-infinity?', () => {
      it('samples', () => {
        expect(dvala.run('negative-infinity?(1)')).toBe(false)
        expect(dvala.run('negative-infinity?(0)')).toBe(false)
        expect(dvala.run('negative-infinity?(1 / 0)')).toBe(false)
        expect(dvala.run('negative-infinity?(-1 / 0)')).toBe(true)
        expect(() => dvala.run('negative-infinity?(sqrt(-1))')).toThrow(DvalaError)
      })
    })

    describe('true?', () => {
      it('samples', () => {
        expect(dvala.run('true?(false)')).toBe(false)
        expect(dvala.run('true?(true)')).toBe(true)
        expect(dvala.run('true?(1)')).toBe(false)
        expect(dvala.run('true?(0)')).toBe(false)
        expect(dvala.run('true?("Mojir")')).toBe(false)
      })
    })

    describe('false?', () => {
      it('samples', () => {
        expect(dvala.run('false?(false)')).toBe(true)
        expect(dvala.run('false?(true)')).toBe(false)
        expect(dvala.run('false?(1)')).toBe(false)
        expect(dvala.run('false?(0)')).toBe(false)
        expect(dvala.run('false?("Mojir")')).toBe(false)
      })
    })

    describe('empty?', () => {
      it('samples', () => {
        expect(dvala.run('empty?([])')).toBe(true)
        expect(dvala.run('empty?([0])')).toBe(false)
        expect(dvala.run('empty?({})')).toBe(true)
        expect(dvala.run('empty?({ a: 2 })')).toBe(false)
        expect(dvala.run('empty?("")')).toBe(true)
        expect(dvala.run('empty?("Albert")')).toBe(false)
        expect(dvala.run('empty?(null)')).toBe(true)

        expect(() => dvala.run('empty?()')).toThrow(DvalaError)
        expect(() => dvala.run('empty?(true)')).toThrow(DvalaError)
        expect(() => dvala.run('empty?(false)')).toThrow(DvalaError)
        expect(() => dvala.run('empty?(10)')).toThrow(DvalaError)
        expect(() => dvala.run('empty?(regexp("^start"))')).toThrow(DvalaError)
      })
    })

    describe('not-empty?', () => {
      it('samples', () => {
        expect(dvala.run('not-empty?([])')).toBe(false)
        expect(dvala.run('not-empty?([0])')).toBe(true)
        expect(dvala.run('not-empty?({})')).toBe(false)
        expect(dvala.run('not-empty?({ a: 2 })')).toBe(true)
        expect(dvala.run('not-empty?("")')).toBe(false)
        expect(dvala.run('not-empty?("Albert")')).toBe(true)
        expect(dvala.run('not-empty?(null)')).toBe(false)

        expect(() => dvala.run('not-(mpty?)')).toThrow(DvalaError)
        expect(() => dvala.run('not-(mpty?)')).toThrow(DvalaError)
        expect(() => dvala.run('not-empty?(true)')).toThrow(DvalaError)
        expect(() => dvala.run('not-empty?(false)')).toThrow(DvalaError)
        expect(() => dvala.run('not-empty?(undefined)')).toThrow(DvalaError)
        expect(() => dvala.run('not-empty?(10)')).toThrow(DvalaError)
        expect(() => dvala.run('not-empty?(regexp("^start"))')).toThrow(DvalaError)
      })
    })

    describe('vector?', () => {
      it('should determine if a value is a vector', () => {
        expect(dvala.run('vector?([])')).toEqual(true)
        expect(dvala.run('vector?([1, 2, 3])')).toEqual(true)
        expect(dvala.run('vector?([1, 2, [3]])')).toEqual(false)
        expect(dvala.run('vector?([1, 2, 3.0])')).toEqual(true)
        expect(dvala.run('vector?([1, 2, "3"])')).toEqual(false)
        expect(dvala.run('vector?([1, 2, true])')).toEqual(false)
        expect(dvala.run('vector?([1, 2, {}])')).toEqual(false)
        expect(dvala.run('vector?(12)')).toEqual(false)
        expect(dvala.run('vector?({})')).toEqual(false)
      })
    })
  }
})
