import { describe, expect, it } from 'vitest'
import { createDvala } from '../../../src/createDvala'
import { DvalaError } from '../../../src/errors'

describe('predicates', () => {
  for (const dvala of [createDvala(), createDvala({ debug: true })]) {
    describe('isFunction', () => {
      it('samples', () => {
        expect(dvala.run('isFunction("")')).toBe(false)
        expect(dvala.run('isFunction("x")')).toBe(false)
        expect(dvala.run('isFunction(1)')).toBe(false)
        expect(dvala.run('isFunction(0)')).toBe(false)
        expect(dvala.run('isFunction([])')).toBe(false)
        expect(dvala.run('isFunction({})')).toBe(false)
        expect(dvala.run('isFunction(null)')).toBe(false)
        expect(dvala.run('isFunction(true)')).toBe(false)
        expect(dvala.run('isFunction(false)')).toBe(false)
        expect(dvala.run('isFunction(+)')).toBe(true)
        expect(dvala.run('isFunction(-> $ - 1)')).toBe(true)
        expect(() => dvala.run('isFunction()')).toThrow(DvalaError)
        expect(() => dvala.run('isFunction("k", "k")')).toThrow(DvalaError)
      })
    })

    describe('isString', () => {
      it('samples', () => {
        expect(dvala.run('isString("")')).toBe(true)
        expect(dvala.run('isString("x")')).toBe(true)
        expect(dvala.run('isString(1)')).toBe(false)
        expect(dvala.run('isString(0)')).toBe(false)
        expect(dvala.run('isString([])')).toBe(false)
        expect(dvala.run('isString({})')).toBe(false)
        expect(dvala.run('isString(null)')).toBe(false)
        expect(dvala.run('isString(true)')).toBe(false)
        expect(dvala.run('isString(false)')).toBe(false)
        expect(dvala.run('isString(+)')).toBe(false)
        expect(dvala.run('isString(+)')).toBe(false)
        expect(() => dvala.run('isString()')).toThrow(DvalaError)
        expect(() => dvala.run('isString("k", "k")')).toThrow(DvalaError)
      })
    })

    describe('isNumber', () => {
      it('samples', () => {
        expect(dvala.run('isNumber(1)')).toBe(true)
        expect(dvala.run('isNumber(0)')).toBe(true)
        expect(dvala.run('isNumber(-1)')).toBe(true)
        expect(dvala.run('isNumber(-1.123)')).toBe(true)
        expect(dvala.run('isNumber(0.123)')).toBe(true)
        expect(dvala.run('isNumber("")')).toBe(false)
        expect(dvala.run('isNumber("x")')).toBe(false)
        expect(dvala.run('isNumber([])')).toBe(false)
        expect(dvala.run('isNumber({})')).toBe(false)
        expect(dvala.run('isNumber(null)')).toBe(false)
        expect(dvala.run('isNumber(false)')).toBe(false)
        expect(dvala.run('isNumber(true)')).toBe(false)
        expect(dvala.run('isNumber(+)')).toBe(false)
        expect(dvala.run('isNumber(+)')).toBe(false)
        expect(() => dvala.run('isNumber()')).toThrow(DvalaError)
        expect(() => dvala.run('isNumber(1, 2)')).toThrow(DvalaError)
      })
    })

    describe('isInteger', () => {
      it('samples', () => {
        expect(dvala.run('isInteger(1)')).toBe(true)
        expect(dvala.run('isInteger(0)')).toBe(true)
        expect(dvala.run('isInteger(-1)')).toBe(true)
        expect(dvala.run('isInteger(-1.123)')).toBe(false)
        expect(dvala.run('isInteger(0.123)')).toBe(false)
        expect(dvala.run('isInteger("")')).toBe(false)
        expect(dvala.run('isInteger("x")')).toBe(false)
        expect(dvala.run('isInteger([])')).toBe(false)
        expect(dvala.run('isInteger({})')).toBe(false)
        expect(dvala.run('isInteger(null)')).toBe(false)
        expect(dvala.run('isInteger(false)')).toBe(false)
        expect(dvala.run('isInteger(true)')).toBe(false)
        expect(dvala.run('isInteger(+)')).toBe(false)
        expect(dvala.run('isInteger(+)')).toBe(false)
        expect(() => dvala.run('isInteger()')).toThrow(DvalaError)
        expect(() => dvala.run('isInteger(1, 2)')).toThrow(DvalaError)
      })
    })

    describe('isBoolean', () => {
      it('samples', () => {
        expect(dvala.run('isBoolean(1)')).toBe(false)
        expect(dvala.run('isBoolean(0)')).toBe(false)
        expect(dvala.run('isBoolean(-1)')).toBe(false)
        expect(dvala.run('isBoolean(-1.123)')).toBe(false)
        expect(dvala.run('isBoolean(0.123)')).toBe(false)
        expect(dvala.run('isBoolean("")')).toBe(false)
        expect(dvala.run('isBoolean("x")')).toBe(false)
        expect(dvala.run('isBoolean([])')).toBe(false)
        expect(dvala.run('isBoolean({})')).toBe(false)
        expect(dvala.run('isBoolean(null)')).toBe(false)
        expect(dvala.run('isBoolean(false)')).toBe(true)
        expect(dvala.run('isBoolean(true)')).toBe(true)
        expect(dvala.run('isBoolean(+)')).toBe(false)
        expect(dvala.run('isBoolean(+)')).toBe(false)
        expect(() => dvala.run('isBoolean()')).toThrow(DvalaError)
        expect(() => dvala.run('isBoolean(true, false)')).toThrow(DvalaError)
      })
    })

    describe('isNull', () => {
      it('samples', () => {
        expect(dvala.run('isNull(1)')).toBe(false)
        expect(dvala.run('isNull(0)')).toBe(false)
        expect(dvala.run('isNull(-1)')).toBe(false)
        expect(dvala.run('isNull(-1.123)')).toBe(false)
        expect(dvala.run('isNull(0.123)')).toBe(false)
        expect(dvala.run('isNull("")')).toBe(false)
        expect(dvala.run('isNull("x")')).toBe(false)
        expect(dvala.run('isNull([])')).toBe(false)
        expect(dvala.run('isNull({})')).toBe(false)
        expect(dvala.run('isNull(null)')).toBe(true)
        expect(dvala.run('isNull(false)')).toBe(false)
        expect(dvala.run('isNull(true)')).toBe(false)
        expect(dvala.run('isNull(+)')).toBe(false)
        expect(dvala.run('isNull(+)')).toBe(false)
        expect(() => dvala.run('isNull()')).toThrow(DvalaError)
        expect(() => dvala.run('isNull(true, false)')).toThrow(DvalaError)
      })
    })

    describe('isZero', () => {
      it('samples', () => {
        expect(dvala.run('isZero(1)')).toBe(false)
        expect(dvala.run('isZero(0)')).toBe(true)
        expect(dvala.run('isZero(0.0)')).toBe(true)
        expect(dvala.run('isZero(-0)')).toBe(true)
        expect(dvala.run('isZero(0 / -1)')).toBe(true)
        expect(dvala.run('isZero(-1)')).toBe(false)
        expect(() => dvala.run('isZero()')).toThrow(DvalaError)
        expect(() => dvala.run('isZero("")')).toThrow(DvalaError)
        expect(() => dvala.run('isZero(true)')).toThrow(DvalaError)
        expect(() => dvala.run('isZero(false)')).toThrow(DvalaError)
        expect(() => dvala.run('isZero(null)')).toThrow(DvalaError)
        expect(() => dvala.run('isZero({})')).toThrow(DvalaError)
        expect(() => dvala.run('isZero([])')).toThrow(DvalaError)
      })
    })

    describe('isPos', () => {
      it('samples', () => {
        expect(dvala.run('isPos(1)')).toBe(true)
        expect(dvala.run('isPos(0.1)')).toBe(true)
        expect(dvala.run('isPos(0)')).toBe(false)
        expect(dvala.run('isPos(-0)')).toBe(false)
        expect(dvala.run('isPos(0 / -1)')).toBe(false)
        expect(dvala.run('isPos(-1)')).toBe(false)
        expect(() => dvala.run('isPos()')).toThrow(DvalaError)
        expect(() => dvala.run('isPos("")')).toThrow(DvalaError)
        expect(() => dvala.run('isPos(true)')).toThrow(DvalaError)
        expect(() => dvala.run('isPos(false)')).toThrow(DvalaError)
        expect(() => dvala.run('isPos(null)')).toThrow(DvalaError)
        expect(() => dvala.run('isPos({})')).toThrow(DvalaError)
        expect(() => dvala.run('isPos([])')).toThrow(DvalaError)
      })
    })

    describe('isNeg', () => {
      it('samples', () => {
        expect(dvala.run('isNeg(1)')).toBe(false)
        expect(dvala.run('isNeg(0)')).toBe(false)
        expect(dvala.run('isNeg(-0)')).toBe(false)
        expect(dvala.run('isNeg(0 / -1)')).toBe(false)
        expect(dvala.run('isNeg(-1)')).toBe(true)
        expect(() => dvala.run('isNeg()')).toThrow(DvalaError)
        expect(() => dvala.run('isNeg("")')).toThrow(DvalaError)
        expect(() => dvala.run('isNeg(true)')).toThrow(DvalaError)
        expect(() => dvala.run('isNeg(false)')).toThrow(DvalaError)
        expect(() => dvala.run('isNeg(null)')).toThrow(DvalaError)
        expect(() => dvala.run('isNeg({})')).toThrow(DvalaError)
        expect(() => dvala.run('isNeg([])')).toThrow(DvalaError)
      })
    })

    describe('isEven', () => {
      it('samples', () => {
        expect(dvala.run('isEven(1)')).toBe(false)
        expect(dvala.run('isEven(0)')).toBe(true)
        expect(dvala.run('isEven(-0)')).toBe(true)
        expect(dvala.run('isEven(0 / -1)')).toBe(true)
        expect(dvala.run('isEven(-1)')).toBe(false)
        expect(dvala.run('isEven(-10)')).toBe(true)
        expect(dvala.run('isEven(-2.001)')).toBe(false)
        expect(dvala.run('isEven(4)')).toBe(true)
        expect(() => dvala.run('isEven()')).toThrow(DvalaError)
        expect(() => dvala.run('isEven("")')).toThrow(DvalaError)
        expect(() => dvala.run('isEven(true)')).toThrow(DvalaError)
        expect(() => dvala.run('isEven(false)')).toThrow(DvalaError)
        expect(() => dvala.run('isEven(null)')).toThrow(DvalaError)
        expect(() => dvala.run('isEven({})')).toThrow(DvalaError)
        expect(() => dvala.run('isEven([])')).toThrow(DvalaError)
      })
    })

    describe('isOdd', () => {
      it('samples', () => {
        expect(dvala.run('isOdd(1)')).toBe(true)
        expect(dvala.run('isOdd(0)')).toBe(false)
        expect(dvala.run('isOdd(-0)')).toBe(false)
        expect(dvala.run('isOdd(0 / -1)')).toBe(false)
        expect(dvala.run('isOdd(-1)')).toBe(true)
        expect(dvala.run('isOdd(-10)')).toBe(false)
        expect(dvala.run('isOdd(-2.001)')).toBe(false)
        expect(dvala.run('isOdd(4)')).toBe(false)
        expect(dvala.run('isOdd(5)')).toBe(true)
        expect(() => dvala.run('isOdd()')).toThrow(DvalaError)
        expect(() => dvala.run('isOdd("")')).toThrow(DvalaError)
        expect(() => dvala.run('isOdd(true)')).toThrow(DvalaError)
        expect(() => dvala.run('isOdd(false)')).toThrow(DvalaError)
        expect(() => dvala.run('isOdd(null)')).toThrow(DvalaError)
        expect(() => dvala.run('isOdd({})')).toThrow(DvalaError)
        expect(() => dvala.run('isOdd([])')).toThrow(DvalaError)
      })
    })

    describe('isArray', () => {
      it('samples', () => {
        expect(dvala.run('isArray(1)')).toBe(false)
        expect(dvala.run('isArray(0)')).toBe(false)
        expect(dvala.run('isArray(-1)')).toBe(false)
        expect(dvala.run('isArray(-1.123)')).toBe(false)
        expect(dvala.run('isArray(0.123)')).toBe(false)
        expect(dvala.run('isArray("")')).toBe(false)
        expect(dvala.run('isArray("x")')).toBe(false)
        expect(dvala.run('isArray([])')).toBe(true)
        expect(dvala.run('isArray([1, 2, 3])')).toBe(true)
        expect(dvala.run('isArray({})')).toBe(false)
        expect(dvala.run('isArray(null)')).toBe(false)
        expect(dvala.run('isArray(false)')).toBe(false)
        expect(dvala.run('isArray(true)')).toBe(false)
        expect(dvala.run('isArray(+)')).toBe(false)
        expect(() => dvala.run('isArray()')).toThrow(DvalaError)
        expect(() => dvala.run('isArray(true, false)')).toThrow(DvalaError)
      })
    })

    describe('isCollection', () => {
      it('samples', () => {
        expect(dvala.run('isCollection(1)')).toBe(false)
        expect(dvala.run('isCollection(0)')).toBe(false)
        expect(dvala.run('isCollection(-1)')).toBe(false)
        expect(dvala.run('isCollection(-1.123)')).toBe(false)
        expect(dvala.run('isCollection(0.123)')).toBe(false)
        expect(dvala.run('isCollection("")')).toBe(true)
        expect(dvala.run('isCollection("x")')).toBe(true)
        expect(dvala.run('isCollection([])')).toBe(true)
        expect(dvala.run('isCollection([1, 2, 3])')).toBe(true)
        expect(dvala.run('isCollection({})')).toBe(true)
        expect(dvala.run('isCollection({ a: 1 })')).toBe(true)
        expect(dvala.run('isCollection(null)')).toBe(false)
        expect(dvala.run('isCollection(false)')).toBe(false)
        expect(dvala.run('isCollection(true)')).toBe(false)
        expect(dvala.run('isCollection(+)')).toBe(false)
        expect(dvala.run('isCollection(+)')).toBe(false)
        expect(() => dvala.run('isCollection()')).toThrow(DvalaError)
        expect(() => dvala.run('isCollection(true, false)')).toThrow(DvalaError)
      })
    })

    describe('isSequence', () => {
      it('samples', () => {
        expect(dvala.run('isSequence(1)')).toBe(false)
        expect(dvala.run('isSequence(0)')).toBe(false)
        expect(dvala.run('isSequence(-1)')).toBe(false)
        expect(dvala.run('isSequence(-1.123)')).toBe(false)
        expect(dvala.run('isSequence(0.123)')).toBe(false)
        expect(dvala.run('isSequence("")')).toBe(true)
        expect(dvala.run('isSequence("x")')).toBe(true)
        expect(dvala.run('isSequence([])')).toBe(true)
        expect(dvala.run('isSequence([1, 2, 3])')).toBe(true)
        expect(dvala.run('isSequence({})')).toBe(false)
        expect(dvala.run('isSequence({ a: 1 })')).toBe(false)
        expect(dvala.run('isSequence(null)')).toBe(false)
        expect(dvala.run('isSequence(false)')).toBe(false)
        expect(dvala.run('isSequence(true)')).toBe(false)
        expect(dvala.run('isSequence(+)')).toBe(false)
        expect(dvala.run('isSequence(+)')).toBe(false)
        expect(() => dvala.run('isSequence()')).toThrow(DvalaError)
        expect(() => dvala.run('isSequence(true, false)')).toThrow(DvalaError)
      })
    })

    describe('isObject', () => {
      it('samples', () => {
        expect(dvala.run('isObject(1)')).toBe(false)
        expect(dvala.run('isObject(0)')).toBe(false)
        expect(dvala.run('isObject(-1)')).toBe(false)
        expect(dvala.run('isObject(-1.123)')).toBe(false)
        expect(dvala.run('isObject(0.123)')).toBe(false)
        expect(dvala.run('isObject("")')).toBe(false)
        expect(dvala.run('isObject("x")')).toBe(false)
        expect(dvala.run('isObject([])')).toBe(false)
        expect(dvala.run('isObject(object("x", 10))')).toBe(true)
        expect(dvala.run('isObject(null)')).toBe(false)
        expect(dvala.run('isObject(regexp("abc"))')).toBe(false)
        expect(dvala.run('isObject(false)')).toBe(false)
        expect(dvala.run('isObject(true)')).toBe(false)
        expect(dvala.run('isObject(+)')).toBe(false)
        expect(dvala.run('isObject(+)')).toBe(false)
        expect(() => dvala.run('isObject()')).toThrow(DvalaError)
        expect(() => dvala.run('isObject(true, false)')).toThrow(DvalaError)
      })
    })

    describe('isRegexp', () => {
      it('samples', () => {
        expect(dvala.run('isRegexp(1)')).toBe(false)
        expect(dvala.run('isRegexp(0)')).toBe(false)
        expect(dvala.run('isRegexp(-1)')).toBe(false)
        expect(dvala.run('isRegexp(-1.123)')).toBe(false)
        expect(dvala.run('isRegexp(0.123)')).toBe(false)
        expect(dvala.run('isRegexp("")')).toBe(false)
        expect(dvala.run('isRegexp("x")')).toBe(false)
        expect(dvala.run('isRegexp([])')).toBe(false)
        expect(dvala.run('isRegexp(object("x", 10))')).toBe(false)
        expect(dvala.run('isRegexp(null)')).toBe(false)
        expect(dvala.run('isRegexp(regexp("abc"))')).toBe(true)
        expect(dvala.run('isRegexp(false)')).toBe(false)
        expect(dvala.run('isRegexp(true)')).toBe(false)
        expect(dvala.run('isRegexp(+)')).toBe(false)
        expect(dvala.run('isRegexp(+)')).toBe(false)
        expect(() => dvala.run('isRegexp()')).toThrow(DvalaError)
        expect(() => dvala.run('isRegexp(true, false)')).toThrow(DvalaError)
      })
    })

    describe('isTrue', () => {
      it('samples', () => {
        expect(dvala.run('isTrue(false)')).toBe(false)
        expect(dvala.run('isTrue(true)')).toBe(true)
        expect(dvala.run('isTrue(1)')).toBe(false)
        expect(dvala.run('isTrue(0)')).toBe(false)
        expect(dvala.run('isTrue("Mojir")')).toBe(false)
      })
    })

    describe('isFalse', () => {
      it('samples', () => {
        expect(dvala.run('isFalse(false)')).toBe(true)
        expect(dvala.run('isFalse(true)')).toBe(false)
        expect(dvala.run('isFalse(1)')).toBe(false)
        expect(dvala.run('isFalse(0)')).toBe(false)
        expect(dvala.run('isFalse("Mojir")')).toBe(false)
      })
    })

    describe('isEmpty', () => {
      it('samples', () => {
        expect(dvala.run('isEmpty([])')).toBe(true)
        expect(dvala.run('isEmpty([0])')).toBe(false)
        expect(dvala.run('isEmpty({})')).toBe(true)
        expect(dvala.run('isEmpty({ a: 2 })')).toBe(false)
        expect(dvala.run('isEmpty("")')).toBe(true)
        expect(dvala.run('isEmpty("Albert")')).toBe(false)
        expect(dvala.run('isEmpty(null)')).toBe(true)

        expect(() => dvala.run('isEmpty()')).toThrow(DvalaError)
        expect(() => dvala.run('isEmpty(true)')).toThrow(DvalaError)
        expect(() => dvala.run('isEmpty(false)')).toThrow(DvalaError)
        expect(() => dvala.run('isEmpty(10)')).toThrow(DvalaError)
        expect(() => dvala.run('isEmpty(regexp("^start"))')).toThrow(DvalaError)
      })
    })

    describe('isNotEmpty', () => {
      it('samples', () => {
        expect(dvala.run('isNotEmpty([])')).toBe(false)
        expect(dvala.run('isNotEmpty([0])')).toBe(true)
        expect(dvala.run('isNotEmpty({})')).toBe(false)
        expect(dvala.run('isNotEmpty({ a: 2 })')).toBe(true)
        expect(dvala.run('isNotEmpty("")')).toBe(false)
        expect(dvala.run('isNotEmpty("Albert")')).toBe(true)
        expect(dvala.run('isNotEmpty(null)')).toBe(false)

        expect(() => dvala.run('not-(mpty?)')).toThrow(DvalaError)
        expect(() => dvala.run('not-(mpty?)')).toThrow(DvalaError)
        expect(() => dvala.run('isNotEmpty(true)')).toThrow(DvalaError)
        expect(() => dvala.run('isNotEmpty(false)')).toThrow(DvalaError)
        expect(() => dvala.run('isNotEmpty(undefined)')).toThrow(DvalaError)
        expect(() => dvala.run('isNotEmpty(10)')).toThrow(DvalaError)
        expect(() => dvala.run('isNotEmpty(regexp("^start"))')).toThrow(DvalaError)
      })
    })

    describe('isVector', () => {
      it('should determine if a value is a vector', () => {
        expect(dvala.run('isVector([])')).toEqual(true)
        expect(dvala.run('isVector([1, 2, 3])')).toEqual(true)
        expect(dvala.run('isVector([1, 2, [3]])')).toEqual(false)
        expect(dvala.run('isVector([1, 2, 3.0])')).toEqual(true)
        expect(dvala.run('isVector([1, 2, "3"])')).toEqual(false)
        expect(dvala.run('isVector([1, 2, true])')).toEqual(false)
        expect(dvala.run('isVector([1, 2, {}])')).toEqual(false)
        expect(dvala.run('isVector(12)')).toEqual(false)
        expect(dvala.run('isVector({})')).toEqual(false)
      })
    })

    describe('isGrid', () => {
      it('should determine if a value is a grid', () => {
        expect(dvala.run('isGrid([])')).toEqual(false)
        expect(dvala.run('isGrid([[]])')).toEqual(false)
        expect(dvala.run('isGrid([[1, 2], [3, 4]])')).toEqual(true)
        expect(dvala.run('isGrid([[1, 2], [3, 4], [5, 6]])')).toEqual(true)
        expect(dvala.run('isGrid([[1, 2], [3, 4], [5, "6"]])')).toEqual(true)
        expect(dvala.run('isGrid([[1, 2], [3, 4], [5, {}]])')).toEqual(true)
        expect(dvala.run('isGrid(12)')).toEqual(false)
        expect(dvala.run('isGrid({})')).toEqual(false)
      })
    })

    describe('isMatrix', () => {
      it('should determine if a value is a matrix', () => {
        expect(dvala.run('isMatrix([])')).toEqual(false)
        expect(dvala.run('isMatrix([[]])')).toEqual(false)
        expect(dvala.run('isMatrix([[1, 2], [3, 4]])')).toEqual(true)
        expect(dvala.run('isMatrix([[1, 2], [3, 4], [5, 6]])')).toEqual(true)
        expect(dvala.run('isMatrix([[1, 2], [3, 4], [5, "6"]])')).toEqual(false)
        expect(dvala.run('isMatrix([[1, 2], [3, 4], [5, {}]])')).toEqual(false)
        expect(dvala.run('isMatrix(12)')).toEqual(false)
        expect(dvala.run('isMatrix({})')).toEqual(false)
      })
    })
  }
})
