export const specialExpressionTypes = {
  '??': '??',
  '&&': '&&',
  '||': '||',
  'array': 'array',
  'block': 'block',
  '0_lambda': '0_lambda',
  'for': 'for',
  'if': 'if',
  'let': 'let',
  'loop': 'loop',
  'object': 'object',
  'recur': 'recur',
  'match': 'match',
  'import': 'import',
  'effect': 'effect',
  'perform': 'perform',
  'parallel': 'parallel',
  'race': 'race',
  'handle': 'handle',
} as const
