export const specialExpressionTypes = {
  '??': 0,
  '&&': 1,
  '||': 2,
  'array': 3,
  'block': 4,
  'doseq': 5,
  '0_lambda': 6,
  'for': 7,
  'if': 8,
  'let': 9,
  'loop': 10,
  'object': 11,
  'recur': 12,
  'match': 13,
  'import': 14,
  'effect': 15,
  'perform': 16,
  'parallel': 17,
  'race': 18,
  'handle': 19,
} as const
